name: sirf-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pyyaml
  - numpy
  - pandas
  - geopy
  - scikit-learn
  - seaborn
  - geopandas
  - matplotlib
  - scipy
  - pip
  - pip:
      - tqdm
      - haversine
      - cartopy